version: 3
env:
  COMPOSE: docker-compose

tasks:
  setup:
    deps: [container-build, up]
    cmds:
      - echo 'setup done'
  container-build:
    internal: true
    cmd: $COMPOSE build
  up:
    internal: true
    cmd: $COMPOSE up -d
  down:
    cmd: $COMPOSE down
  install:
    # pnpm installを実行するTask
    cmd: $COMPOSE run --rm node pnpm install
  add:ui:
    # shadcn-uiからのコンポーネントの追加をするTask
    # 例: task add:ui -- button
    cmd: $COMPOSE run --rm node pnpm dlx shadcn-ui@latest add {{.CLI_ARGS}}

